### ISSUE TITLE
Errors installing setup.py

### ISSUE THREAD

**Issue by kimjh069** [lanfeng4659/STR-TDSL#6]
Hi, thanks for sharing such a great work.

I was wondering if I could run my sample images with your model.
But I could not figure out how to install setup.py

I ran `python setup.py install` within my conda virtual environment, but I got error messages.

Can you provide instructions on how to install?
And also sample code to run your code with any sample image?

**Comment by lanfeng4659** [comment]
python setup.py install develop

The environment is the same as https://github.com/facebookresearch/maskrcnn-benchmark

We give the evaluation pipeline in the readme. Just put the images in the corresponding folder. Then run the test.sh script.

**Comment by lanfeng4659** [comment]
> Hi, thanks for sharing such a great work.
> 
> I was wondering if I could run my sample images with your model. But I could not figure out how to install setup.py
> 
> I ran `python setup.py install` within my conda virtual environment, but I got error messages.
> 
> Can you provide instructions on how to install? And also sample code to run your code with any sample image?

python setup.py install develop

The environment is the same as https://github.com/facebookresearch/maskrcnn-benchmark

We give the evaluation pipeline in the readme. Just put the images in the corresponding folder. Then run the test.sh script.

**Comment by kimjh069** [comment]
Hi,
Thank you for your previous support.

I am currently facing an issue when trying to download the trained model. I was able to successfully install the software, following the instructions provided. However, I seem to be encountering a roadblock at the step where I am supposed to download the trained model.

I attempted to download the file from [Baidu Disk](https://pan.baidu.com/s/1vLR4EzXYyof-l69b621jog)(legq), and I obtained a file named baidunetdisk_4.17.7_amd64.deb. However, I was unable to find the .pth file for the trained model within this download.

Could you please provide some guidance on this matter? 
Have I missed a step in the process or is there an additional download source for the .pth file?

I look forward to your assistance.

**Comment by lanfeng4659** [comment]
> Hi, Thank you for your previous support.
> 
> I am currently facing an issue when trying to download the trained model. I was able to successfully install the software, following the instructions provided. However, I seem to be encountering a roadblock at the step where I am supposed to download the trained model.
> 
> I attempted to download the file from [Baidu Disk](https://pan.baidu.com/s/1vLR4EzXYyof-l69b621jog)(legq) by clicking "(129.6M)下载", and I obtained a file named baidunetdisk_4.17.7_amd64.deb. However, I was unable to find the .pth file for the trained model within this download.
> 
> Could you please provide some guidance on this matter? Have I missed a step in the process or is there an additional download source for the .pth file?
> 
> I look forward to your assistance.

The file baidunetdisk_4.17.7_amd64.deb is the installer of the Baidu Disk software in a Linux system. The link I provide is the checkpoint of the trained model named "model 7709.pth" that is stored in the Baidu Disk .  So, you might download a wrong file.

As I know, you can register an account of Baidu Disk, then click the link I provide. You will jump a web page that login in your registered account. At last, you can see the file (as shown in the following picture) and download it.
![image](https://github.com/lanfeng4659/STR-TDSL/assets/29145165/37b46dcc-0ded-4d10-81e3-e88d15d7aaba)

**Comment by kimjh069** [comment]
Thank you.
After registering an account of Baidu Disk, I could download the file.
Closing this issue.
